<?php require_once 'class.user.php'; ?>
    <!DOCTYPE html>
    <html lang="en">

    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Terms and Conditions</title>
        <!-- css includes-->
        <?php include"source.php" ?>
    </head>

    <body>
        <?php 
	include_once("analyticstracking.php");
  if(isset($_SESSION['userSession']))
        {
             include "postlogin-header-jobseekar.php"; 
        } 
     
	else if(isset($_SESSION['empSession']))
        {
             include "includes-recruiter/db-recruiter-header.php"; 
        } 
		else
	{
    include "prelogin-header2.php"; 
  } 
	?>
            <!-- main-->
            <main>
                <!-- page title -->
                <section class="page-title-block">
                    <div class="container">
                        <article class="page-titlein">
                            <h2 class="h2 flight txt-white">Terms of <span class="fbold"> Services</span></h2>
                           <!-- <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. </p> -->
                        </article>
                    </div>
                </section>
                <!--/ page title -->
                <!-- page static content body -->
                <section class="page-content">
                    <div class="container">
                        <div class="row">
                            <div class="col-md-12">
                                <div class="privacy-policy">
                                    <p class="pb15 text-justify">This disclaimer is issued by Needyin Pvt. Ltd, MR House, Indian Airlines Colony, Begumpet, Hyderabad - 500016, Telangana (hereinafter referred to as NI); which is the registered owner of Needyin and governs your use of our website, www.Needyin.com (hereinafter referred to as “our website”). By using our website, you accept this disclaimer in full. </p>
                                    <p class="pb15 text-justify">Needyin Pvt. Ltd. will not be liable on account of any inaccuracy of information on our website. It is the responsibility of the visitor to further research the information on the site. Any breach of privacy or of the information provided by the consumer to NI to be placed on our website by technical or any other means is not the responsibility of NI. NI does not guarantee the confidentiality of information provided to it by any person acquiring/using all/any information displayed on the Needyin website or any of its other websites/domains owned and operated by Needyin Pvt. Ltd..</p>
                                    <p class="pb15 text-justify">Needyin Pvt. Ltd. does not share personally identifiable data of any individual with other companies/entities without obtaining permission except with those acting as our agents or recruiters or Affiliates defined as any person directly or indirectly controlling, controlled by, or under direct or indirect common control with Needyin, including its subsidiaries and associate companies. NI shall share all such information that it has in its possession in response to legal processes, such as a court order or subpoena. The user shall not utilize the services offered by Needyin/NI in any manner so as to impair the interests and functioning of Needyin/NI. The user undertakes not to duplicate, download publish, modify and distribute material on Needyin unless specifically authorized by Needyin Pvt. Ltd. in this regard. The user undertakes not to establish any deep link or other connection to any specific page of Needyin.com other than the Home Page without obtaining the prior consent of Needyin Pvt. Ltd..</p>
                                    <p class="pb15 text-justify">The user undertakes to use Needyin for his/her own purposes. Using content from Needyin for derivative works with a commercial motive without prior written consent from Needyin Pvt. Ltd. is strictly prohibited. </p>
                                    <p class="pb15 text-justify">Needyin uses technological means to exclude Robots etc from crawling the website and scraping content. The user undertakes not to circumvent these methods.</p>
                                    <p class="pb15 text-justify">Users undertake that the services offered by Needyin/NI shall not be utilized to upload, post, e-mail, transmit or otherwise make available either directly or indirectly, any unsolicited bulk e-mail or unsolicited commercial e-mail. NI reserves the right to filter and monitor and block the e-mails sent by you/user using the servers maintained by NI to relay e-mails. All attempts shall be made by NI and the user to abide by International Best Practices in containing and eliminating spams.</p>
                                    <p class="pb15 text-justify">Users shall not spam the database maintained by Needyin/NI or indiscriminately and repeatedly forward e-mail that may be considered spam etc. Any conduct of the user in violation of this clause shall entitle NI to forthwith terminate all services to the user without notice and to forfeit any amounts paid by him.</p>
                                    <p class="pb15 text-justify">The user shall not upload, post, transmit, publish, or distribute any material or information that is unlawful, or which may potentially be perceived as being harmful, threatening, abusive, harassing, defamatory, libelous, vulgar, obscene, or racially, ethnically, or otherwise objectionable.</p>
                                    <p class="pb15 text-justify">The user expressly states that the resume/profile information/data being fed into the network of NI by the user is correct and complete in all respects and does not contain any false, distorted, manipulated, fraudulent or misleading facts or averments. NI expressly disclaims any liability arising out of the said resume/profile information/data so fed into the network of NI by the user. </p>
                                    <p class="pb15 text-justify">Further, the user agrees to indemnify NI for all losses incurred by NI due to any false, distorted, manipulated, defamatory, libelous, vulgar, obscene, fraudulent or misleading facts or otherwise objectionable averments made by the user on the network of NI.</p>
                                    <p class="pb15 text-justify">The user is solely responsible for maintaining confidentiality of the user password and user identification and all activities and transmission performed by the user through his/her user identification and shall be solely responsible for carrying out any online or off-line transaction involving credit cards/debit cards or such other forms of instruments or documents for making such transactions and NI assumes no responsibility or liability for their improper use of information relating to such usage of credit cards/debit cards used by the subscriber online/offline.</p>
                                    <p class="pb15 text-justify">The User/Subscriber/Visitor to Needyin and/or its affiliated websites does hereby specifically agree that he/she shall, at all times, comply with the requirements of the Information Technology Act, 2000 as also rules, regulations, guidelines, by-laws and notifications made thereunder, while assessing or feeding any resume/profile information/data into the computers, computer systems or computer network of Needyin Pvt. Ltd. The said user/subscriber/visitor to Needyin and/or its affiliated websites does further unequivocally declare that in case he violates any provisions of the Information Technology Act, 2000 and/or rules, regulations, guidelines, by-laws and notifications made thereunder, he shall alone be responsible for all his acts, deeds and things and that he alone shall be liable for civil and criminal liability thereunder or under any other law for the time being in force.</p>
                                    <p class="pb15 text-justify">The user is solely responsible for obtaining, at his own cost, all licenses, permits, consents, approvals and intellectual property or other rights as may be required by the user for using the Service.</p>
                                    <p class="pb15 text-justify">The User/Subscriber/Visitor to Needyin or affiliated site(s) is prohibited from uploading, posting, transmitting, updating or sharing: any information that:</p>
                                    <ul class="static-list">
                                        <li>Belongs to another person and to which the user does not have any right to;</li>
                                        <li>Is grossly harmful, harassing, blasphemous, defamatory, obscene, pornographic, paedophilic, libelous, invasive of another's privacy, hateful, or racially, ethnically objectionable, disparaging, relating or encouraging money laundering or gambling, or otherwise unlawful in any manner whatever; harm minors in any way;/li>
                                            <li>Infringes any patent, trademark, copyright or other proprietary rights;</li>
                                            <li>Violates any law for the time being in force;</li>
                                            <li>Deceives or misleads the addressee about the origin of such messages or communicates any information which is grossly offensive or menacing in nature; impersonate another person;</li>
                                            <li>Contains software viruses or any other computer code, files or programs designed to interrupt, destroy or limit the functionality of any computer resource; threatens the unity, integrity, defence, security or sovereignty of India, friendly relations with foreign states, or public order or causes incitement to the commission of any cognisable offence or prevents investigation of any offence or is insulting any other nation.</li>
                                    </ul>
                                    <p class="pb15 text-justify">The user shall not infringe on any intellectual property rights of any person/entity or retain information/download any information from any computer system or otherwise with an intention to do so.</p>
                                    <p class="pb15 text-justify">Needyin Pvt. Ltd. will make best efforts to do so but does not warrant that any of the websites or any affiliate site(s) or network system linked to it is free of any operational errors nor does it warrant that it will be free of any virus, computer contaminant, worm, or other harmful components. E-mails provided as part of contact details are expected to be genuine and access to such email accounts is available to authorized personnel only.</p>
                                    <p class="pb15 text-justify">Needyin Pvt. Ltd. shall not be liable for any loss or damage sustained by reason of any disclosure (inadvertent or otherwise) of any information concerning the user's account and/or information relating to or regarding online transactions using credit cards/debit cards and/or their verification process and particulars nor for any error, omission or inaccuracy with respect to any information so disclosed and used whether or not in pursuance of a legal process or otherwise.</p>
                                    <p class="pb15 text-justify">Payments for the services offered by Needyin shall be on a 100% advance basis. Refund if any will be at the sole discretion of NI. Needyin Pvt. Ltd. offers no guarantees whatsoever for the accuracy or timeliness of the refunds reaching the Customers card/bank accounts. NI gives no guarantees of server uptime or applications working properly. All is on a best effort basis and liability is Ltd. to refund of amount only. NI undertakes no liability for free services. NI reserves its right to amend/alter or change all or any disclaimers or terms of agreements at any time without any prior notice. All terms/disclaimers whether specifically mentioned or not shall be deemed to be included if any reference is made to them.</p>
                                    <p class="pb15 text-justify">Needyin Pvt. Ltd. further reserves its right to post the data on the website www.Needyin.com or on such other affiliated sites and publications as Needyin Pvt. Ltd. may deem fit and proper at no extra cost to the subscriber/user.</p>
                                    <p class="pb15 text-justify">The subscription/agreement between Needyin Pvt. Ltd. and the subscriber/user is not a "non-poach agreement" nor can the same be termed or used as an alternative to "non-poach agreement" in as much as NI/Needyin is a public site and all information posted by NI goes to the public domain except information/data which is specifically assigned to a non-public/Pvt. character.</p>
                                    <p class="pb15 text-justify">Any agreement for a subscription/usage entered into by Needyin Pvt. Ltd. does not confer exclusivity of service on any subscriber/user.</p>
                                    <p class="pb15 text-justify">Needyin Pvt. Ltd. will not be party to any legal proceedings between a user (e.g. a subscriber) and a party contracted through the site. In case NI is implicated in any legal proceedings, costs will be recovered from the party that names NI. NI, however will abide with any court order served on it through due process.</p>
                                    <p class="pb15 text-justify">In case a person using the world wide web/internet receives a spam or virus which includes a link to www.Needyin.com or to any other site maintained, operated or owned by Needyin Pvt. Ltd., it should not be held responsible for the same. Needyin Pvt. Ltd. assumes no responsibility for such emails.</p>
                                    <p class="pb15 text-justify">The services provided by the websites maintained, operated or owned by Needyin Pvt. Ltd. do not extend to acting as an agent (express or implied) on behalf of any subscriber or user.</p>
                                    <p class="pb15 text-justify">Needyin Pvt. Ltd. has no agents and does not operate through any agents save for those specifically mentioned on the home page of the website.</p>
                                    <p class="pb15 text-justify">The Terms and conditions mentioned above regulate the usage of Needyin. Any person using Needyin in violation of the stipulations contained in the Terms and Conditions of Needyin shall render himself/herself liable to appropriate action in a court of law both civil and criminal.</p>
                                    <p class="pb15 text-justify">The user of Needyin is subject to the Privacy Policy available through this link.</p>
                                    <p class="pb15 text-justify">In case of non-compliance of these Terms and Conditions or Privacy Policy NI may terminate usage rights and take down any offending information that might have been uploaded by such subscriber/user.</p>
                                    <h4 class="fbold h4 txt-blue">Job Seekers</h4>
                                    <p class="pb15 text-justify">By registering your profile or uploading your resume to www.Needyin.com you agree to the following terms.</p>
                                    <ul class="static-list">
                                        <li>The resume/profile information/data fed by the user can be updated by the user alone, free of cost.</li>
                                        <li>NI offers no guarantee nor warranties that there would be a satisfactory response or any response at all once the resume/profile information/data is fed by the user.</li>
                                        <li>NI neither guarantees nor offers any warranty about the credentials bonafide, status or otherwise of the prospective employer/organization which downloads the resume/profile information/data and uses it to contact the user.</li>
                                        <li>NI would not be held liable for loss of any data technical or otherwise, or of the resume/profile information/data or particulars supplied by user due to acts of God as well as reasons beyond its control like corruption of data or delay or failure to perform as a result of any cause(s) or conditions that are beyond NI’s reasonable control including but not Ltd. to strikes, riots, civil unrest, Govt. policies, tampering of data by unauthorized persons like hackers, distributed denial of service attacks, virus attacks, war and natural calamities.</li>
                                        <li>It shall be sole prerogative and responsibility of the user to check the authenticity of all or any response received pursuant to the resume/profile information/data being fed into the network system of NI by the user, for going out of station or in station for any job or interview. NI assumes no responsibility in respect thereof and expressly disclaims any liability for any act, deed or thing which the user may so do, pursuant to the receipt of the response, if any, to the resume/profile information/data being fed into the network system of NI.</li>
                                        <li>Uploading of multiple resume/profiles beyond a reasonable limit by the same individual, using the same or different accounts shall entitle NI to remove the Resume/profiles without notice to the subscriber. This service is only meant for candidates looking for suitable jobs. Any usage with commercial intent is prohibited.</li>
                                        <li>NI reserves its right to reject and delete any resume/profile information/data fed in by the user without assigning any reason.</li>
                                        <li>This free service entitles the user alone ie. the same person, to add modify or change the data/information fed in by him but does not entitle him to use the free service to feed fresh insertion or information/data/resume/profile of another person in place of the insertion or information/data already fed in by such user.</li>
                                        <li>NI has the right to make all such modifications/editing of resume/profile in order to fit resume/profile in its database.</li>
                                        <li>It shall be the sole responsibility of the user to ensure that it uses the privacy setting options as it deems fit to debar/refuse access of the data fed by it, to such corporate entities individuals or consultants. NI shall not be responsible for such insertions/data being accessed by its subscribers or users whose access has not been specifically blocked/debarred by the user while using the privacy settings.</li>
                                        <li>Although NI will make all possible efforts to adhere to these privacy settings, it will not be responsible for a resume/profile being seen by a blocked user for any reason. For best privacy settings it is recommended that you do not allow your resume/profile to be searched at all.</li>
                                        <li>The user represents that he/she is not a minor and is not under any legal or other disability which limits his/her ability to comply with these Terms or to install and use the services subscribed and purchased with minimal risk of harm to you or others. You further represent that you are not purchasing the products/services for resale to others and will not do so without NI’s prior written consent.</li>
                                        <li>All changes/modifications made by the user to the data/information shall be effected and will come into operation only after 24-48 hours of such changes/modifications being made.</li>
                                    </ul>
                                    <p class="pb15 text-justify">On registration you agree to: a) Needyin Pvt. Ltd. contacting you via email and/or telephone to verify the information available on your profile. b) Making your profile/resume searchable to the clients of Needyin Pvt. Ltd.. c) You may be contacted by recruiters via email, telephone and/or post. If you wish to not be contacted you need to deactivate your account. We recommend that you read the privacy settings carefully and Needyin Pvt. Ltd. will not be held responsible for contacts/mails received by you. d) Receive job alerts (mails detailing jobs that match your profile as entered on Needyin) via email. You may remove yourself from the job alert email database by resetting this option in the Setting section of your resume/profile e) Receive promotional mailers/special offers. You may remove yourself from the promotional mailer email database by resetting this option on the Setting section of your resume/profile.</p>
                                    <p class="pb15 text-justify">NI uses an automated algorithm to match jobs against the keywords/attributes present in the profile submitted by the user, and hence offers no guarantee nor warranties that the jobs sent in the job mail will be relevant to the profile.</p>
                                    <p class="pb15 text-justify">NI neither guarantees nor offers any warranty about the credentials of the prospective employer/organization whose details are sent in the job mail.</p>
                                    <p class="pb15 text-justify">Although all attempts will be made by NI to send all jobs on the specified days, however it does not take any responsibility for job mail not been sent (which may be on account of non-availability of jobs as per the user's specified criteria).</p>
                                    <p class="pb15 text-justify">NI will not be responsible in any way for failure of any backend technology of mail exchange server and resultant inability of a user to receive job mail.</p>
                                    <p class="pb15 text-justify">NI reserves the right to regulate number of jobs sent out in the Job mail to a particular user in a single day.</p>
                                    <p class="pb15 text-justify">The user agreement between a user/subscriber and Needyin Pvt. Ltd. will be treated as having been terminated in the following events: (i) On completion of the term for which the user/subscriber engages the services of the website; or (ii) In case the user/subscriber violates any of the conditions of this agreement or any other agreement entered into by him with Needyin Pvt. Ltd., however, such termination will be at the option and discretion of Needyin Pvt. Ltd. ; or (iii) On writing and on such terms as agreed to by the parties mutually.</p>
                                    <p class="pb15 text-justify">NI would not be held liable for loss of any data technical or otherwise and particulars supplied by subscribers due to reasons beyond its control like corruption of data or delay or failure to perform as a result of any causes or conditions that are beyond Needyin reasonable control including but not Ltd. to strikes, riots, civil unrest, Govt. policies, tampering of data by unauthorized persons like hackers, war and natural calamities.</p>
                                    <p class="pb15 text-justify">The User of these services does not claim any copyright or other Intellectual Property Right over the data uploaded by him/her on the website.</p>
                                    <p class="pb15 text-justify">Jurisdiction for any disputes arising from and related to this contest shall be Bengaluru, India to the exclusion of all other courts.</p>
                                    <p class="pb15 text-justify">Disputes shall be resolved in accordance with the laws of India as applicable</p>
                                    <h4 class="fbold h4 txt-blue">Non Registered Users</h4>
                                    <p class="pb15 text-justify">The user undertakes that the data/information being provided by him/her in the resume /profile is true and correct in all respects.</p>
                                    <p class="pb15 text-justify">Needyin Pvt. Ltd. does not share personally identifiable data of any individual with other companies/entities without obtaining permission except with those acting as our agents or recruiters or affiliates defined as any person directly or indirectly controlling, controlled by, or under direct or indirect common control with, Needyin, including its subsidiaries and associate companies. Needyin Pvt. Ltd. may share all such information that it has in its possession for its own purposes including sending promotional mailers etc. and in response to legal process, such as a court order or subpoena.</p>
                                    <p class="pb15 text-justify">The user undertakes that he/she will not disseminate false/objectionable/offensive material using these services.</p>
                                    <p class="pb15 text-justify">This interface shall be exclusively for the purposes of bona fide job applications; usage of the interface in any other fashion is strictly prohibited.</p>
                                    <p class="pb15 text-justify">Needyin Pvt. Ltd. neither guarantees nor offers any warranty about the credentials bonafide, status or otherwise of the prospective employer/organization which downloads the resume /profile/ insertion or information/data and uses it to contact the user.</p>
                                    <p class="pb15 text-justify">The user shall not infringe on any intellectual property rights of any person/entity or retain information/download any information from any computer system or otherwise with an intention to do so.</p>
                                    <p class="pb15 text-justify">The User/subscriber/visitor to Needyin or affiliated site(s) is prohibited from introducing/posting or transmitting information or software, which contains a computer virus, or a contaminant, worm or other harmful components on the internet or on hiree.com site or sub-domains or on any affiliate sites or any other network system</p>
                                    <p class="pb15 text-justify">Needyin Pvt. Ltd. will not be party to any legal proceedings between a user (e.g. a subscriber) and a party contracted through the site. In case Needyin Pvt. Ltd. is implicated in any legal proceedings, costs will be recovered from the party that names Needyin Pvt. Ltd.. NeedyinTech however will abide with any court order served on it through due process.</p>
                                    <p class="pb15 text-justify">Jurisdiction for any disputes arising from and related to this contest shall be Hyderabad, India to the exclusion of all other courts.</p>
                                    <p class="pb15 text-justify">Disputes shall be resolved in accordance with the laws of India as applicable.</p>
                                    <h4 class="fbold h4 txt-blue">Recruiter</h4>
                                    <p class="pb15 text-justify">Needyin Pvt. Ltd. shall place the information relating to vacancies on Needyin jobs board or such other classified sections on the website www.Needyin.com or such other mirror or parallel site(s) or in allied publications as NI may deem fit and proper but such additional web hosting shall be without any extra cost to the subscriber/user.</p>
                                    <p class="pb15 text-justify">The insertion so displayed in the classified section of Needyin shall be for a fixed period, which period is subject to change without notice. Every instance of refreshing and existing listing entitles you to and additional fixed period starting from the date on which the listing is refreshed and shall be counted as fresh posting.</p>
                                    <p class="pb15 text-justify">Needyin Pvt. Ltd. offers no guarantee nor warranties that there would be a satisfactory response or any response at all subscriber for applications.</p>
                                    <p class="pb15 text-justify">Needyin Pvt. Ltd. shall in no way be held liable for any information received by the subscriber and it shall be the sole responsibility of the subscriber to check, authenticate and verify the information/response received at its own cost and expense.</p>
                                    <p class="pb15 text-justify">Any actions taken by an employer/recruiter on the basis of the background check report or otherwise, is the employer's/recruiter's responsibility alone and NI will not be liable in any manner for the consequences of such action taken by the user.</p>
                                    <p class="pb15 text-justify">Needyin Pvt. Ltd. reserves its right to suspend/terminate the services contracted for by the subscriber either prior to or during the contracted period without assigning any reason. In such an eventuality, any amount so paid for by the subscriber for this service, may be refunded by NI at a prorata basis to the subscriber at its discretion.</p>
                                    <p class="pb15 text-justify">Needyin Pvt. Ltd. reserves its right to reject any insertion or information/data provided by the subscriber without assigning any reason either before uploading or after uploading the vacancy details, but in such an eventuality, any amount so paid for, may be refunded to the subscriber on a pro-rata basis at the sole discretion of NI.</p>
                                    <p class="pb15 text-justify">By posting/uploading a job posting on the website you confirm that you have obtained all licenses/permits as are necessary for recruitment and to indemnify Needyin Pvt. Ltd. against all claims, damages arising out of actions/claims that may be made in relation to the same.</p>
                                    <p class="pb15 text-justify">Needyin Pvt. Ltd. has the right to make all such modifications/editing of the vacancy details in order to fit its database.</p>
                                    <p class="pb15 text-justify">All information intimated by the subscriber/recruiter and displayed by NI on Needyin becomes public knowledge and NI may at its sole discretion include the vacancy intimated by a subscriber for display on Needyin in any other media including the print media at no extra costs to the subscriber and NI shall not be held liable for usage/publicity of such information.</p>
                                    <p class="pb15 text-justify">NI offers no guarantee nor warranties that there would be a satisfactory response or any at all response once the job is put on display.</p>
                                    <p class="pb15 text-justify">NI shall in no way be held liable for any information received by the subscriber and it shall be the sole responsibility of the subscriber to check, authenticate and verify the information/response received at its own cost and expense.</p>
                                    <p class="pb15 text-justify">NI would not be held liable for any loss of data, technical or otherwise, information, particulars supplied by the subscriber, due the reasons beyond its control like corruption of data or delay or failure to perform as a result of any causes or conditions that are beyond NI’s reasonable control including but not Ltd. to strike, riots, civil unrest, Govt. policies, tampering of data by unauthorized persons like hackers, war and natural calamities.</p>
                                    <p class="pb15 text-justify">Needyin Pvt. Ltd. will commence providing services only upon receipt of amount/charges upfront either from the subscriber or from a third party on behalf of the subscriber.</p>
                                    <p class="pb15 text-justify">The Subscriber/Recruiter shall be deemed to give an undertaking to NI that the jobs sought to be advertised on the classified section of Needyin are in existence, are genuine and that the subscriber/recruiter has the authority to advertise for such jobs.</p>
                                    <p class="pb15 text-justify">Needyin Pvt. Ltd. will commence providing services only upon receipt of amount/charges upfront either from the subscriber or from a third party on behalf of the subscriber.</p>
                                    <p class="pb15 text-justify">The Subscriber/Recruiter must give an undertaking to NI that there will be no fee charged from any person who responds to jobs advertised on the classified section of Needyin for processing of applications/responses from such person.</p>
                                    <p class="pb15 text-justify">NI reserves its right to change the look, feel, design, prominence, depiction and classification of the classified section of Needyin at any time without assigning any reason and without giving any notice.</p>
                                    <p class="pb15 text-justify">The subscriber can select password’s to post vacancies on the site in agreed upon section(s), but the sole responsibility of the safe custody of the password shall be that of the subscriber and NI shall not be responsible for data loss/theft of data/corruption of data or the wrong usage/misuse of the password and any damage or leak of information and its consequential usage by a third party. NI undertakes to take all reasonable precautions at its end to ensure that there is no leakage/misuse of the password granted to the subscriber.</p>
                                    <p class="pb15 text-justify">The information on NI is for use by its subscribers alone and does not authorize the subscriber to download and use the data for commercial purposes. In case of violation NI at its discretion may suspend its service/subscription and also may take such action as it may be advised.</p>
                                    <p class="pb15 text-justify">The subscriber shall not use/circulate/forward a person's resume/profile hosted on the NI Network to his/her current employer as mentioned by the person in his / her resume /profile.</p>
                                    <p class="pb15 text-justify">The User of these services does not claim any copyright or other Intellectual Property Right over the data uploaded by him/her on the website</p>
                                    <p class="pb15 text-justify">All disputes arising out of the transactions between a user and NI will be resolved in accordance with the laws of India as applicable.</p>
                                    <p class="pb15 text-justify">All Disputes arising out of the transactions between a user and NI will be subject to the jurisdiction of Courts situate in Hyderabad alone.</p>
                                    <h4 class="fbold h4 txt-blue">Charges</h4>
                                    <p class="pb15 text-justify">This Site reserves the right to charge subscription and/or membership fees in respect of any part, aspect of this Site upon reasonable prior notice. NI reserves its right to terminate your account without any prior notice for any violation of the Terms of Use. All content posted by you becomes the property of NI and you agree to grant/assign the royalty free, perpetual right to use, reproduce, modify, adapt, publish, translate, create derivative works from, distribute, perform and display such content (in whole or part) worldwide and/or to incorporate it in other works in any form, media or technology now known or later developed.</p>
                                    <h4 class="fbold h4 txt-blue">Disclaimer of Warranties and Liability</h4>
                                    <p class="pb15 text-justify">All the contents of this Site are only for general information or use. They do not constitute advice and should not be relied upon in making (or refraining from making) any decision. Any specific advice or replies to queries in any part of the site is/are the personal opinion of such experts/consultants/persons and are not subscribed to by this Site. The information from or through this site is provided on "AS IS" basis, and all warranties, expressed or implied of any kind, regarding any matter pertaining to any goods, service or channel, including without limitation, the implied warranties of merchantability, fitness for a particular purpose, and non-infringement are disclaimed and excluded. Certain links on the Site lead to resources located on servers maintained by third parties over whom NI has no control or connection, business or otherwise as these sites are external to NI you agree and understand that by visiting such sites you are beyond the Needyin website. NI therefore neither endorses nor offers any judgment or warranty and accepts no responsibility or liability for the authenticity/availability of any of the goods/services/or for any damage, loss or harm, direct or consequential or any violation of local or international laws that may be incurred by your visit and/or transaction/s on these sites.</p>
                                    <h4 class="fbold h4 txt-blue">Advertising Material</h4>
                                    <p class="pb15 text-justify">Part of the Site might contain advertising/other material submitted to NI by third parties. Responsibility for ensuring that material submitted for inclusion on the site complies with applicable International and National law is exclusively on the advertisers and NI will not be responsible for any claim, error, omission or inaccuracy in advertising material. NI reserves the right to omit, suspend or change the position of any advertising material submitted for insertion. Acceptance of advertisements on the Site will be subject to NI terms and conditions which are available on request.</p>
                                    <h4 class="fbold h4 txt-blue">Force Majeure</h4>
                                    <p class="pb15 text-justify">NI shall have no liability to you for any interruption or delay in access to the Site irrespective of the cause.</p>
                                    <h4 class="fbold h4 txt-blue">Indian Law</h4>
                                    <p class="pb15 text-justify">The Agreement shall be governed by the Laws of India. The Courts of law at Hyderabad shall have exclusive jurisdiction over any disputes arising under this agreement.</p>
                                    <h4 class="fbold h4 txt-blue">ANTI SPAM POLICY</h4>
                                    <p class="pb15 text-justify">The use and access to jobseeker data is subject to this policy. The services provided to you are aimed at providing recruitment solutions and should be restricted to contacting suitable candidates for genuine jobs in existence.</p>
                                    <p class="pb15 text-justify">Mailing practices such as transmitting marketing and promotional mailers/ Offensive messages/ messages with misleading subject lines in order to intentionally obfuscate the original message, are strictly prohibited.</p>
                                    <p class="pb15 text-justify">We reserve the right to terminate services, without prior notice, to the originator of Spam. No refund shall be admissible under such circumstances.</p>
                                    <p class="pb15 text-justify">Following is an illustrative (not exhaustive) list of the kinds of messages which can be classified as spam:</p>
                                    <ul class="static-list">
                                        <li>Unsolicited Bulk Messages/Unsolicited Commercial Communications.</li>
                                        <li>Voice Calls/SMS to telephone numbers registered on the National Consumer Preference Register.</li>
                                        <li>Non Job related mails.</li>
                                        <li>Messages with misleading subject lines.</li>
                                        <li>Blank Messages.</li>
                                        <li>Extra ordinary High Number of mails.</li>
                                        <li>Mails soliciting payments.</li>
                                    </ul>
                                    <p class="pb15 text-justify">Users agree to indemnify and hold harmless NI from any damages or claims arising out of usage for transmitting spam.</p>
                                    <p class="pb15 text-justify">Users are advised to change their passwords frequently in order to reduce the possibility of misuse of their accounts.</p>
                                    <p class="pb15 text-justify">To seek more information and to report Spam. Please mail us at: info@Needyin.com. </p>
                                    <p class="pb15 text-justify"><span class="fbold">Note:</span> The terms in this agreement may be changed by Needyin Pvt. Ltd. at any time. NI is free to offer its services to any client/prospective client without restriction.</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </section>
                <!--/ page static content body -->
            </main>
            <!--/main-->
            <?php //include"footer.php"?>
    </body>

    </html>