from nltk.corpus import stopwords

# NeedyIn Technology
NAME_PATTERN      = [{'POS': 'PROPN'}, {'POS': 'PROPN'}]

# Education (Upper Case Mandatory)
EDUCATION         = [
                    'BE','B.E.', 'B.E', 'BS', 'B.S', 'ME', 'M.E', 'M.E.', 'MS', 'M.S', 'BTECH', 'MTECH', 
                    'SSC', 'HSC', 'CBSE', 'ICSE', 'X', 'XII','Intermediate','10th','12th','10+2'
                    ]

NOT_ALPHA_NUMERIC = r'[^a-zA-Z\d]'

NUMBER            = r'\d+'

# For finding date ranges
MONTHS_SHORT      = r'(jan)|(feb)|(mar)|(apr)|(may)|(jun)|(jul)|(aug)|(sep)|(oct)|(nov)|(dec)'
MONTHS_LONG       = r'(january)|(february)|(march)|(april)|(may)|(june)|(july)|(august)|(september)|(october)|(november)|(december)'
MONTH             = r'(' + MONTHS_SHORT + r'|' + MONTHS_LONG + r')'
YEAR              = r'(((20|19)(\d{2})))'

STOPWORDS         = set(stopwords.words('english'))

RESUME_SECTIONS_PROFESSIONAL = [
                    'experience',
                    'education',
		            'email address',
                    'computer proficiency',
                    'operating systems',
                    'software',
                    'testing tools',
                    'defect tracking',
                    'database',
                    'interests',
                    'Research and Development Experience',
                    'Research Interests',
                    'ML Programming Skills',
                    'ML Library Skills',
                    'ML Algorithm Skills',
                    'Cloud Platform',
                    'Additional Programing Skills',
                    'Education',
                    'Linkedin profile',
                    'GitHub profile',
                    'skype',
                    'working at',
                    'worked at',
                    'professional experience',
                    'Previous Experience',
                    'publications',
                    'skills',
                    'certifications',
                    'objective',
                    'career objective',
                    'summary',
                    'leadership'
                    'accomplishments',
                    'experience',
                    'education',
                    'email',
		            'email address',
                    'Research and Development Experience',
                    'Research Interests',
                    'ML Programming Skills',
                    'ML Library Skills',
                    'ML Algorithm Skills',
                    'Cloud Platform',
                    'Additional Programing Skills',
                    'education',
                    'linkedin profile',
                    'gitHub profile',
                    'skype',
                    'working at',
                    'worked at',
                    'interests',
                    'projects',
                    'computer proficiency',
                    'operating systems',
                    'software',
                    'testing tools',
                    'defect tracking',
                    'database',
                    'professional experience',
                    'publications',
                    'skills',
                    'certifications',
                    'objective',
                    'career objective',
                    'summary',
                    'leadership'
                     'NAME',
                     'E-mail',
                     'Gender',
                     'Marital Status',
                     'Domains',
                     'Passport No',
                     'Contact',
                     'Mobile',
                     'Address',
                     'Location',
                     'Designation',
                     'PROFILE',
                     'Professional Experience',
                     'PROFILE SUMMARY',
                     'Professional Overview',
                     'Current_Company_&_Duration',
                     'Previous_Company’s',
                     'Total_Experience',
                     'Experience_Relevant',
                     'Skills_Relevant',
                     'Preferred_Skills',
                     'Non_Technical_Skills',
                     'SKILLS',
                     'Technical Skills',
                     'EXPERIENCE',
                     'Educational Qualifications',
                     'Education',
                     'Key Skills',
                     'Frameworks',
                     'Database',
                     'Languages Known',
                     'Platform',
                     'Web Technologies',
                     'Development Environment',
                     'Parsing Technique',
                     'API Knows',
                     'IDE',
                     'OS',
                     'Certification',
                     'TECHNICAL',
                     'EXPERIENCE',
                     'WORK EXPERIENCE',
                     'Professional experience',
                     'EDUCATION',
                     'PROJECTS',
                     'Projects',
                     'Title',
                     'Project Title',
                     'Client',
                     'Tools',
                     'Role',
                     'Roles and Responsibility',
                     'Responsibilities',
                     'Team Size',
                     'Languages',
                     'Project Details',
                     'Organization',
                     'Features',
                     'Contribution',
                     'Environment',
                     'Project #1',
                     'Project #2',
                     'Project #3',
                     'Project #4',
                     'Project #5',
                     'Project #6',
                     'Project 1',
                     'Project 2',
                     'Project 3',
                     'Project 4',
                     'Project 5',
                     'Project 6',
                     'Duration',
                     'Software',
                     'Job Role',
                     'Description',
                     'WORKSHOPS',
                     'Languages Known',
                     'ACHIEVEMENTS',
                     'Hobbies',
                     'Key Responsibilities',
                     'AWARDS',
                     'ACTIVITIES',
                     'Nationality',
                     'References',
                     'Conferences and Publications'
                  

                ]

RESUME_SECTIONS_GRAD = [
                     'name',
                     'email',
                     'phone number',
                     'designation',
                     'professional experience',
                     'relevant experience',
                     'work experience',
                     'job profile',
                     'summary',
                     'internship',
                     'freelancing',
                     'technical skills',
                     'non technical skills',
                     'key role',
                     'web technologies',
                     'technologies',
                     'frameworks',
                     'server',
                     'ide',
                     'environment',
                     'programming_language',
                     'networking',
                     'education',
                     'current company wise duration',
                     'previous company',
                     'role',
                     'location',
                     'projects',
                     'project name',
                     'project title',
                     'client',
                     'project description',
                     'project details',
                     'duration',
                     'hosting platforms',
                     'operating system',
                     'responsibilities',
                     'certification',
                     'achievement',
                     'contributions',
                     'database',
                     'tools',
                     'computer proficiency',
                     'other keywords',
                     'domain',
                     'testing tool',
                     'organization',
                     'soft_skills',
                     'product',
                     'team size'
                    'accomplishments',
                    'experience',
                    'education',
                    'email',
		            'email address',
                    'Research and Development Experience',
                    'Research Interests',
                    'ML Programming Skills',
                    'ML Library Skills',
                    'ML Algorithm Skills',
                    'Cloud Platform',
                    'Additional Programing Skills',
                    'education',
                    'linkedin profile',
                    'gitHub profile',
                    'skype',
                    'working at',
                    'worked at',
                    'interests',
                    'projects',
                    'computer proficiency',
                    'operating systems',
                    'software',
                    'testing tools',
                    'defect tracking',
                    'database',
                    'professional experience',
                    'publications',
                    'skills',
                    'certifications',
                    'objective',
                    'career objective',
                    'summary',
                    'leadership'
                ]

COMPETENCIES = {
    'teamwork': [
        'supervised',
        'facilitated',
        'planned',
        'plan',
        'served',
        'serve',
        'project lead',
        'managing',
        'managed',
        'lead ',
        'project team',
        'team',
        'conducted',
        'worked',
        'gathered',
        'organized',
        'mentored',
        'assist',
        'review',
        'help',
        'involve',
        'share',
        'support',
        'coordinate',
        'cooperate',
        'contributed'
    ],
    'communication': [
        'addressed',
        'collaborated',
        'conveyed',
        'enlivened',
        'instructed',
        'performed',
        'presented',
        'spoke',
        'trained',
        'author',
        'communicate',
        'define',
        'influence',
        'negotiated',
        'outline',
        'proposed',
        'persuaded',
        'edit',
        'interviewed',
        'summarize',
        'translate',
        'write',
        'wrote',
        'project plan',
        'business case',
        'proposal',
        'writeup'
    ],
    'analytical': [
        'process improvement',
        'competitive analysis',
        'aligned',
        'strategive planning',
        'cost savings',
        'researched ',
        'identified',
        'created',
        'led',
        'measure',
        'program',
        'quantify',
        'forecasr',
        'estimate',
        'analyzed',
        'survey',
        'reduced',
        'cut cost',
        'conserved',
        'budget',
        'balanced',
        'allocate',
        'adjust',
        'lauched',
        'hired',
        'spedup',
        'speedup',
        'ran',
        'run',
        'enchanced',
        'developed'
    ],
    'result_driven': [
        'cut',
        'decrease',
        'eliminate',
        'increase',
        'lower',
        'maximize',
        'rasie',
        'reduce',
        'accelerate',
        'accomplish',
        'advance',
        'boost',
        'change',
        'improve',
        'saved',
        'save',
        'solve',
        'solved',
        'upgrade',
        'fix',
        'fixed',
        'correct',
        'achieve'           
    ],
    'leadership': [
        'advise',
        'coach',
        'guide',
        'influence',
        'inspire',
        'instruct',
        'teach',
        'authorized',
        'chair',
        'control',
        'establish',
        'execute',
        'hire',
        'multi-task',
        'oversee',
        'navigate',
        'prioritize',
        'approve',
        'administer',
        'preside',
        'enforce',
        'delegate',
        'coordinate',
        'streamlined',
        'produce',
        'review',
        'supervise',
        'terminate',
        'found',
        'set up',
        'spearhead',
        'originate',
        'innovate',
        'implement',
        'design',
        'launch',
        'pioneer',
        'institute'
    ]
}

MEASURABLE_RESULTS = {
        'metrics': [
        'saved',
        'increased',
        '$ ',
        '%',
        'percent',
        'upgraded',
        'fundraised ',
        'millions',
        'thousands',
        'hundreds',
        'reduced annual expenses ',
        'profits',
        'growth',
        'sales',
        'volume',
        'revenue',
        'reduce cost',
        'cut cost',
        'forecast',
        'increase in page views',
        'user engagement',
        'donations',
        'number of cases closed',
        'customer ratings',
        'client retention',
        'tickets closed',
        'response time',
        'average',
        'reduced customer complaints',
        'managed budget',
        'numeric_value'
    ],
    'action_words': [
        'developed',
        'led',
        'analyzed',
        'collaborated',
        'conducted',
        'performed',
        'recruited',
        'improved',
        'founded',
        'transformed',
        'composed',
        'conceived',
        'designed',
        'devised',
        'established',
        'generated',
        'implemented',
        'initiated',
        'instituted',
        'introduced',
        'launched',
        'opened',
        'originated',
        'pioneered',
        'planned',
        'prepared',
        'produced',
        'promoted',
        'started',
        'released',
        'administered',
        'assigned',
        'chaired',
        'consolidated',
        'contracted',
        'co-ordinated',
        'delegated',
        'directed',
        'evaluated',
        'executed',
        'organized',
        'oversaw',
        'prioritized',
        'recommended',
        'reorganized',
        'reviewed',
        'scheduled',
        'supervised',
        'guided',
        'advised',
        'coached',
        'demonstrated',
        'illustrated',
        'presented',
        'taught',
        'trained',
        'mentored',
        'spearheaded',
        'authored',
        'accelerated',
        'achieved',
        'allocated',
        'completed',
        'awarded',
        'persuaded',
        'revamped',
        'influenced',
        'assessed',
        'clarified',
        'counseled',
        'diagnosed',
        'educated',
        'facilitated',
        'familiarized',
        'motivated',
        'participated',
        'provided',
        'referred',
        'rehabilitated',
        'reinforced',
        'represented',
        'moderated',
        'verified',
        'adapted',
        'coordinated',
        'enabled',
        'encouraged',
        'explained',
        'informed',
        'instructed',
        'lectured',
        'stimulated',
        'classified',
        'collated',
        'defined',
        'forecasted',
        'identified',
        'interviewed',
        'investigated',
        'researched',
        'tested',
        'traced',
        'interpreted',
        'uncovered',
        'collected',
        'critiqued',
        'examined',
        'extracted',
        'inspected',
        'inspired',
        'summarized',
        'surveyed',
        'systemized',
        'arranged',
        'budgeted',
        'controlled',
        'eliminated',
        'itemised',
        'modernised',
        'operated',
        'organised',
        'processed',
        'redesigned',
        'reduced',
        'refined',
        'resolved',
        'revised',
        'simplified',
        'solved',
        'streamlined',
        'appraised',
        'audited',
        'balanced',
        'calculated',
        'computed',
        'projected',
        'restructured',
        'modelled',
        'customized',
        'fashioned',
        'integrated',
        'proved',
        'revitalized',
        'set up',
        'shaped',
        'structured',
        'tabulated',
        'validated',
        'approved',
        'catalogued',
        'compiled',
        'dispatched',
        'filed',
        'monitored',
        'ordered',
        'purchased',
        'recorded',
        'retrieved',
        'screened',
        'specified',
        'systematized',
        'conceptualized',
        'brainstomed',
        'tasked',
        'supported',
        'proposed',
        'boosted',
        'earned',
        'negotiated',
        'navigated',
        'updated',
        'utilized'
    ],
    'weak_words': [
        'i',
        'got',
        'i\'ve',
        'because',
        'our',
        'me',
        'he',
        'her',
        'him',
        'she',
        'helped',
        'familiar',
        'asssisted',
        'like',
        'enjoy',
        'love',
        'did',
        'tried',
        'attempted',
        'worked',
        'approximately',
        'managed',
        'manage',
        'create',
        'created'
    ]
}
